### PR TITLE
makeLeafObjectHandler

### LINKED ISSUE #124: False positives on diff
### Brief bug description

Getting items on snapshot diff reports that don't seem to differ

### Repro steps

1. diff 2 similar environments -> no difference
2. snapshot one of the environments
3. diff 1 environment to snapshot
4. diff report shows changes, but they don't seem to be different

### Expected behavior

no difference shown in both diffs

### Test environment

 - Platform/OS: MacOS 15.3

### Additional context

I would post a screenshot, but it's validation regex in content types so I don't want to risk a security issue

### PR DESCRIPTION
**Pull request by IvanKiral**
### Motivation

Which issue does this fix? Fixes #124 

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

### CODE REVIEW

File: src/modules/sync/diff/combinators.ts [hunk 1]
```diff
@@ -52,11 +52,16 @@ export const makeLeafObjectHandler = <Entity extends object>(
...
-    .some(([key, [source, target]]) => !(customComparers[key]?.(source, target) ?? source === target));
+  const keys = new Set([
+    ...Object.keys(sourceValue),
+    ...Object.keys(targetValue),
+    ...Object.keys(customComparers),
+  ]) as Set<keyof Entity>;
+
+  const shouldReplace = Array.from(keys)
+    .some(key =>
+      !(customComparers[key]?.(sourceValue[key], targetValue[key]) ?? sourceValue[key] === targetValue[key])
```
Comment (JiriLojda) [inline src/modules/sync/diff/combinators.ts:63]: I know that it was there before, but is this part `sourceValue[key] === targetValue[key]` in the expression correct? I would think that we want to replace the object if any of the properties are different, meaning this expression instead `sourceValue[key] !== targetValue[key]`. Am I missing something? Can you write a test case for this scenario if it is indeed a bug?

**Review by JiriLojda — CHANGES_REQUESTED** [review]

File: src/modules/sync/diff/combinators.ts (hunk 1 above)
Comment (JiriLojda) [reply src/modules/sync/diff/combinators.ts:63]: Oh, I didn't notice the negation is around the whole expression. Everything is alright then.

**Review by JiriLojda — APPROVED** [review]
