### PR TITLE
fix cleaning language when there another languages

### LINKED ISSUE #119: Clean has exceeded language limit
### Brief bug description

I have an environment with the two languages, the maximum number languages allowed in my subscription. After backing up, cleaning, and restoring the environment. It becomes impossible to clean it again as I run into a Validation Error {"message":"The specified project already contains the maximum number of active languages for your subscription plan. To add a new language, deactivate an existing language first."} This is still with two active languages and one inactivate one.

### Repro steps

1. Create as many languages as your subscription allows in an environment.
2. Run a backup
3. Clean the environment.
4. Restore from the backup. 
5. Try to clean the environment again. 

### Expected behavior

Be able to clean the environment as my active languages aren't above the limit. 

### Test environment

 - Platform/OS: [e.g. .NET Core 2.1, iOS]

### Screenshots

Image

Image

### PR DESCRIPTION
**Pull request by IvanKiral**
### Motivation

Which issue does this fix? Fixes #119 

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

### CODE REVIEW

File: src/modules/backupRestore/backupRestoreEntities/entities/languages.ts [hunk 1]
```diff
@@ -15,21 +15,33 @@ export const languagesEntity = {
...
+  importEntities: async (client, { entities, context, options }) => {
     const importDefaultLanguage = entities.find(l =>
       l.id === defaultLanguageId
     ) as LanguageContracts.ILanguageModelContract;
     const projectDefaultLangauge = await client.viewLanguage().byLanguageId(defaultLanguageId).toPromise().then(res =>
       res.data
     );
 
+    const importLanguages = options?.excludeInactiveLanguages
+      ? entities.filter(l => l.id !== defaultLanguageId && l.is_active)
```
Comment (JiriLojda) [inline src/modules/backupRestore/backupRestoreEntities/entities/languages.ts:27]: It's just a detail, but you can merge the two branches into one. Sorting in the branch where there are only active languages doesn't matter and you can add into the filter a condition like this to leave the inactive languages there if `excludeInactiveLanguages` is false. `l.id !== defaultLanguageId && (!options?.excludeInactiveLanguages || l.is_active)`.

**Review by JiriLojda — APPROVED** [review]

File: src/modules/backupRestore/backupRestoreEntities/entities/languages.ts (hunk 1 above)
Comment (IvanKiral) [reply src/modules/backupRestore/backupRestoreEntities/entities/languages.ts]: you are right, I have force-pushed a rewritten solution :)
